### ISSUE TITLE
Js version can't resolve jsr import with entrypoint

### ISSUE THREAD

**Issue by hasundue** [denoland/import_map#78]
```ts
    const importMap = await parseFromJson(
      "file:///a/import-map.json",
      {
        imports: {
          "@std/assert": "jsr:@std/assert",
          "@std/testing": "jsr:@std/testing",
        },
      },
    );
    // This passes
    assertEquals(
      importMap.resolve("@std/assert", "https://deno.land/x/oak/mod.ts"),
      "jsr:@std/assert",
    );
    // This throws
    assertEquals(
      importMap.resolve("@std/testing/bdd", "https://deno.land/x/oak/mod.ts"),
      "jsr:@std/testing/bdd",
    );
```

```
error: Error: Relative import path "@std/testing/bdd" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/oak/mod.ts"
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbindgen_error_new (file:///home/hasundue/import_map/js/import_map.generated.js:247:19)
    at <anonymous> (file:///home/hasundue/import_map/js/import_map_bg.wasm:1:33775)
    at JsImportMap.resolve (file:///home/hasundue/import_map/js/import_map.generated.js:200:12)
    at ImportMap.resolve (file:///home/hasundue/import_map/js/mod.ts:26:24)
    at fn (file:///home/hasundue/import_map/tests/test.ts:76:17)
```

I created a draft PR with a failing case: #77 
Feel free to remove it or maybe I'm fixing it if nobody seems motivated to.
Guessing that the "ext" feature is not included in the wasm code.

**Comment by hasundue** [comment]
Confirmed that enabling the ext feature solves the problem: https://github.com/denoland/import_map/pull/77/commits/988064b4aee51f91e4b079fb35ba0b891d45d7fe

But I'm not sure if this can be the default or not, or how the interface to the option should be provided. Any advice or finalization from the team would be appreciated.

**Comment by hasundue** [comment]
Let me close this since the PR has been merged.
